### PR TITLE
Generic linalg

### PR DESCRIPTION
**Pull request by YingboMa**
With
```julia
using DiffEqGPU, CuArrays, OrdinaryDiffEq


function lorenz(du,u,p,t)
 @inbounds begin
     du[1] = p[1]*(u[2]-u[1])
     du[2] = u[1]*(p[2]-u[3]) - u[2]
     du[3] = u[1]*u[2] - p[3]*u[3]
 end
 nothing
end

CuArrays.allowscalar(false)
u0 = Float32[1.0;0.0;0.0]
tspan = (0.0f0,100.0f0)
p = (10.0f0,28.0f0,8/3f0)
prob = ODEProblem(lorenz,u0,tspan,p)
const pre_p = [rand(Float32,3) for i in 1:100_000]
prob_func = (prob,i,repeat) -> remake(prob,p=pre_p[i].*p)
monteprob = EnsembleProblem(prob, prob_func = prob_func)
```

I get `dtmin` error only on the GPU.

```julia
julia> solve(monteprob,TRBDF2(linsolve=LinSolveGPUSplitFactorize()),EnsembleGPUArray(),dt=0.1,trajectories=2,saveat=1.0f0)
┌ Warning: dt <= dtmin. Aborting. There is either an error in your model specification or the true solution is unstable.
└ @ DiffEqBase ~/.julia/dev/DiffEqBase/src/integrator_interface.jl:162
EnsembleSolution Solution of length 2 with uType:
ODESolution{Float32,2,Array{Array{Float32,1},1},Nothing,Nothing,Array{Float32,1},Nothing,ODEProblem{Array{Float32,1},Tuple{Float32,Float32},true,Array{Float32,1},ODEFunction{true,typeof(lorenz),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem},TRBDF2{0,true,LinSolveGPUSplitFactorize,NLNewton{Rational{Int64},Rational{Int64},Rational{Int64}},DataType},DiffEqBase.LinearInterpolation{Array{Float32,1},Array{Array{Float32,1},1}},DiffEqBase.DEStats}

julia> solve(monteprob,TRBDF2(linsolve=LinSolveGPUSplitFactorize()),EnsembleCPUArray(),dt=0.1,trajectories=2,saveat=1.0f0)
EnsembleSolution Solution of length 2 with uType:
ODESolution{Float32,2,Array{Array{Float32,1},1},Nothing,Nothing,Array{Float32,1},Nothing,ODEProblem{Array{Float32,1},Tuple{Float32,Float32},true,Array{Float32,1},ODEFunction{true,typeof(lorenz),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem},TRBDF2{0,true,LinSolveGPUSplitFactorize,NLNewton{Rational{Int64},Rational{Int64},Rational{Int64}},DataType},DiffEqBase.LinearInterpolation{Array{Float32,1},Array{Array{Float32,1},1}},DiffEqBase.DEStats}
```

@ChrisRackauckas could you take a look?

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
@vchuravy we discussed this one. Essentially `EnsembleGPUArray` runs it on the GPU and `EnsembleCPUArray` runs it on the CPU. Both use exactly the same GPUifyLoops code, just with a switch:

```julia
                version = u isa CuArray ? CUDA() : CPU()
                @launch version jac_kernel(jac,J,u,p,t)
```

for example, so it's exactly the "same code" on our end. But the answer is different, and numerically unstable for the GPU. You mentioned this may be because of extra manipulations done only for the GPU, and that there is a part of GPUifyLoops we should try commenting out.

**Comment by vchuravy** [comment]
x-ref: https://github.com/vchuravy/GPUifyLoops.jl/issues/91 and https://github.com/vchuravy/GPUifyLoops.jl/pull/55 

So commenting out:
https://github.com/vchuravy/GPUifyLoops.jl/blob/5ca1301e04c684ac9e3816fd8d7847f361470f36/src/context.jl#L138-L140

to check if that is indeed the issue.

**Comment by YingboMa** [comment]
The issue still presents without those lines. It doesn't seem like a numerical stability issue, because it fails at the very first step.

**Comment by ChrisRackauckas** [comment]
```
("before", A) = ("before", Float32[-5269.86 6.70119 0.0 0.0 0.0 0.0; 2.35988 -5264.16 -1.0 0.0 0.0 0.0; 0.0 1.0 -5264.2 0.0 0.0 0.0; -3.34872 3.34872 0.0 -5263.16 0.0 0.0; 21.098 -1.0 -1.0 0.0 -5263.16 0.0; 0.0 1.0 -0.0391261 
0.0 0.0 -5263.16])
("after", A) = ("after", Float32[-5269.86 6.70119 0.0 0.0 0.0 0.0; 2.35988 -5264.16 -1.0 0.0 0.0 0.0; 0.0 1.0 -5264.2 0.0 0.0 0.0; -3.34872 3.34872 0.0 -5263.16 0.0 0.0; 21.098 -1.0 -1.0 -0.0 -5263.16 0.0; 0.0 1.0 -0.0391261 -0.0 -0.0 -5263.16])
┌ Warning: NaN dt detected. Likely a NaN value in the state, parameters, or derivative value caused this outcome.└ @ DiffEqBase C:\Users\accou\.julia\dev\DiffEqBase\src\integrator_interface.jl:150
("before", A) = ("before", Float32[-5269.86 6.70119 0.0 0.0 0.0 0.0; 2.35988 -5264.16 -1.0 0.0 0.0 0.0; 0.0 1.0 -5264.2 0.0 0.0 0.0; -3.34872 3.34872 0.0 -5263.16 0.0 0.0; 21.098 -1.0 -1.0 0.0 -5263.16 0.0; 0.0 1.0 -0.0391261 
0.0 0.0 -5263.16])
("after", A) = ("after", Float32[-5269.86 6.70119 0.0 0.0 0.0 0.0; -0.000447807 -5264.15 -1.0 0.0 0.0 0.0; -0.0 -0.000189964 -5264.2 0.0 0.0 0.0; -3.34872 3.34872 0.0 -5263.16 0.0 0.0; 21.098 -1.0 -1.0 -0.0 -5263.16 0.0; 0.0 1.0 -0.0391261 -0.0 -0.0 -5263.16])
```

The view doesn't on the GPU doesn't seem to keep a link to the original array?

**Comment by YingboMa** [comment]
```julia
julia> W = Float32[-1.7900316e7 5.8979425 0.0 0.0 0.0 0.0 0.0 0.0 0.0; -1.5510927e-6 -1.7900312e7 -1.0 0.0 0.0 0.0 0.0 0.0 0.0; -0.0 -5.5864948e-8 -1.790031e7 0.0 0.0 0.0 0.0 0.0 0.0; -2.762401 2.762401 0.0 -1.790031e7 0.0 0.0 0.0 0.0 0.0; -8.948659 23.719786 -1.0 0.0 -1.790031e7 0.0 0.0 0.0 0.0; -0.0 0.042158898 -1.9165194 0.0 0.0 -1.790031e7 0.0 0.0 0.0; -9.988357 9.988357 0.0 0.0 0.0 0.0 -1.790031e7 0.0 0.0; -0.10235015 0.02230978 -1.0 0.0 0.0 0.0 0.0 -1.790031e7 0.0; -0.0 44.82339 44.394615 0.0 0.0 0.0 0.0 0.0 -1.790031e7]
9×9 Array{Float32,2}:
 -1.79003e7    5.89794      0.0         0.0         0.0         0.0         0.0         0.0         0.0
 -1.55109e-6  -1.79003e7   -1.0         0.0         0.0         0.0         0.0         0.0         0.0
 -0.0         -5.58649e-8  -1.79003e7   0.0         0.0         0.0         0.0         0.0         0.0
 -2.7624       2.7624       0.0        -1.79003e7   0.0         0.0         0.0         0.0         0.0
 -8.94866     23.7198      -1.0         0.0        -1.79003e7   0.0         0.0         0.0         0.0
 -0.0          0.0421589   -1.91652     0.0         0.0        -1.79003e7   0.0         0.0         0.0
 -9.98836      9.98836      0.0         0.0         0.0         0.0        -1.79003e7   0.0         0.0
 -0.10235      0.0223098   -1.0         0.0         0.0         0.0         0.0        -1.79003e7   0.0
 -0.0         44.8234      44.3946      0.0         0.0         0.0         0.0         0.0        -1.79003e7
```

It looks like that the unpacking of the Jacobian matrix is wrong.

**Comment by YingboMa** [comment]
```julia
julia> solve(monteprob,TRBDF2(linsolve=LinSolveGPUSplitFactorize()),EnsembleGPUArray(),dt=0.1,trajectories=2,saveat=1.0f0)
ERROR: InvalidIRError: compiling qr_kernel(Cassette.Context{nametype(Ctx),Nothing,Nothing,GPUifyLoops.var"##PassType#402",Nothing,Cassette.DisableHooks}, typeof(DiffEqGPU.qr_kernel), CUDAnative.CuDeviceArray{Float32,2,CUDAnative.AS.Global}, Int32, Int32) resulted in invalid LLVM IR
Reason: unsupported call to the Julia runtime (call to jl_f_tuple)
Stacktrace:
 [1] overdub at /home/yingbo/.julia/packages/Cassette/YCOeN/src/overdub.jl:524
 [2] checked_trunc_sint at boot.jl:582
 [3] toInt32 at boot.jl:619
 [4] Int32 at boot.jl:709
 [5] convert at number.jl:7
 [6] SimpleView at /home/yingbo/.julia/dev/DiffEqGPU/src/DiffEqGPU.jl:233
 [7] qr_kernel at /home/yingbo/.julia/dev/DiffEqGPU/src/DiffEqGPU.jl:244
 [8] overdub at /home/yingbo/.julia/packages/Cassette/YCOeN/src/overdub.jl:0
Reason: unsupported call to the Julia runtime (call to jl_f_getfield)
Stacktrace:
 [1] throw_inexacterror at boot.jl:560
 [2] overdub at /home/yingbo/.julia/packages/Cassette/YCOeN/src/overdub.jl:0
 [3] checked_trunc_sint at boot.jl:582
 [4] toInt32 at boot.jl:619
 [5] Int32 at boot.jl:709
 [6] convert at number.jl:7
 [7] SimpleView at /home/yingbo/.julia/dev/DiffEqGPU/src/DiffEqGPU.jl:233
 [8] qr_kernel at /home/yingbo/.julia/dev/DiffEqGPU/src/DiffEqGPU.jl:244
 [9] overdub at /home/yingbo/.julia/packages/Cassette/YCOeN/src/overdub.jl:0
Stacktrace:
 [1] check_ir(::CUDAnative.CompilerJob, ::LLVM.Module) at /home/yingbo/.julia/dev/CUDAnative/src/compiler/validation.jl:114
 [2] macro expansion at /home/yingbo/.julia/dev/CUDAnative/src/compiler/driver.jl:188 [inlined]
 [3] macro expansion at /home/yingbo/.julia/packages/TimerOutputs/7zSea/src/TimerOutput.jl:216 [inlined]
 [4] #codegen#136(::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::typeof(CUDAnative.codegen), ::Symbol, ::CUDAnative.CompilerJob) at /home/yingbo/.julia/dev/CUDAnative/src/compiler/driver.jl:186
 [5] #codegen at ./none:0 [inlined]
 [6] #compile#135(::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::typeof(CUDAnative.compile), ::Symbol, ::CUDAnative.CompilerJob) at /home/yingbo/.julia/dev/CUDAnative/src/compiler/driver.jl:47
 [7] #compile at /home/yingbo/.julia/dev/CUDAnative/src/compiler/common.jl:0 [inlined]
 [8] #compile#134 at /home/yingbo/.julia/dev/CUDAnative/src/compiler/driver.jl:28 [inlined]
 [9] #compile at ./none:0 [inlined] (repeats 2 times)
 [10] macro expansion at /home/yingbo/.julia/dev/CUDAnative/src/execution.jl:389 [inlined]
 [11] #cufunction#176(::String, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(CUDAnative.cufunction), ::typeof(Cassette.overdub), ::Type{Tuple{Cassette.Context{nametype(Ctx),Nothing,Nothing,GPUifyLoops.var"##PassType#402",Nothing,Cassette.DisableHooks},typeof(DiffEqGPU.qr_kernel),CUDAnative.CuDeviceArray{Float32,2,CUDAnative.AS.Global},Int32,Int32}}) at /home/yingbo/.julia/dev/CUDAnative/src/execution.jl:357
 [12] (::CUDAnative.var"#kw##cufunction")(::NamedTuple{(:name,),Tuple{String}}, ::typeof(CUDAnative.cufunction), ::Function, ::Type) at ./none:0
 [13] macro expansion at /home/yingbo/.julia/dev/GPUifyLoops/src/GPUifyLoops.jl:126 [inlined]
 [14] macro expansion at ./gcutils.jl:91 [inlined]
 [15] #launch#50(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(GPUifyLoops.launch), ::GPUifyLoops.CUDA, ::typeof(DiffEqGPU.qr_kernel), ::CuArray{Float32,2}, ::Vararg{Any,N} where N) at /home/yingbo/.julia/dev/GPUifyLoops/src/GPUifyLoops.jl:122
 [16] launch at /home/yingbo/.julia/dev/GPUifyLoops/src/GPUifyLoops.jl:120 [inlined]
 [17] macro expansion at /home/yingbo/.julia/dev/GPUifyLoops/src/GPUifyLoops.jl:54 [inlined]
 [18] #call#44 at /home/yingbo/.julia/dev/DiffEqGPU/src/DiffEqGPU.jl:220 [inlined]
 [19] Any at ./none:0 [inlined]
...
```
With the simpler view, the `jl_f_tuple` error shows up again. @vchuravy could you take a look?

The view now looks like this
https://github.com/JuliaDiffEq/DiffEqGPU.jl/pull/17/files#diff-90f5ad9f4eb9fd418f70216b94a00be1R231-R237

**Comment by ChrisRackauckas** [comment]
```julia
using DiffEqGPU, CuArrays, OrdinaryDiffEq

function lorenz(du,u,p,t)
 @inbounds begin
     du[1] = p[1]*(u[2]-u[1])
     du[2] = u[1]*(p[2]-u[3]) - u[2]
     du[3] = u[1]*u[2] - p[3]*u[3]
 end
 nothing
end

function lorenz_jac(J,u,p,t)
 @inbounds begin
     σ = p[1]
     ρ = p[2]
     β = p[3]
     x = u[1]
     y = u[2]
     z = u[3]
     J[1,1] = -σ
     J[2,1] = ρ - z
     J[3,1] = y
     J[1,2] = σ
     J[2,2] = -1
     J[3,2] = x
     J[1,3] = 0
     J[2,3] = -x
     J[3,3] = -β
 end
 nothing
end

func = ODEFunction(lorenz,jac=lorenz_jac)

CuArrays.allowscalar(false)
u0 = Float32[1.0;0.0;0.0]
tspan = (0.0f0,0.01f0)
p = (10.0f0,28.0f0,8/3f0)
prob = ODEProblem(func,u0,tspan,p)
const pre_p = [rand(Float32,3) for i in 1:100_000]
prob_func = (prob,i,repeat) -> remake(prob,p=pre_p[i].*p)
monteprob = EnsembleProblem(prob, prob_func = prob_func)

solve(monteprob,TRBDF2(linsolve=LinSolveGPUSplitFactorize()),EnsembleGPUArray(),dt=0.01,adaptive=false,trajectories=2,saveat=1.0f0
)
solve(monteprob,TRBDF2(linsolve=LinSolveGPUSplitFactorize()),EnsembleCPUArray(),dt=0.01,adaptive=false,trajectories=2,saveat=1.0f0
)
```

The factorization still does nothing on the GPU even with the launch config.

**Comment by YingboMa** [comment]
With
```julia
function __printjac(A, ii)
    @cuprintf "[%d, %d]\n" ii.offset1 ii.stride2
    @cuprintf "%d %d %d\n%d %d %d\n%d %d %d\n" ii[1, 1] ii[1, 2] ii[1, 3] ii[2, 1] ii[2, 2] ii[2, 3] ii[3, 1] ii[3, 2] ii[3, 3]
    @cuprintf "%2.2f %2.2f %2.2f\n%2.2f %2.2f %2.2f\n%2.2f %2.2f %2.2f" A[ii[1, 1]] A[ii[1, 2]] A[ii[1, 3]] A[ii[2, 1]] A[ii[2, 2]] A[ii[2, 3]] A[ii[3, 1]] A[ii[3, 2]] A[ii[3, 3]]
end
```

I got

```julia
(p.len, p.nfacts) = (3, 2)


outer factorization loop


before lufact!
[3, 0]
22 0 28
0 34 0
23 0 29
-38.23 4.09 0.00
11.48 -35.14 -1.00
0.00 1.00 -35.99
inner factorization loop
L
L
U
U
U
U
inner factorization loop
L
U
inner factorization loop
after lufact![3, 0]
22 0 28
0 34 0
23 0 29
-38.23 4.09 0.00
-0.30 -33.91 -1.00
-0.00 -0.03 -36.02
```
`SimpleView` misbehaves in GPU. Note the
```julia
[3, 0]
22 0 28
0 34 0
23 0 29
```
which means that the offset is 3 and the stride is 0, which is wrong. It should be `[0, 6]`. `ii[1:3, 1:3]` is completely wrong, too. 

Also with `trajectories=1`, i.e.
```julia
julia> solve(monteprob,TRBDF2(linsolve=LinSolveGPUSplitFactorize()),EnsembleGPUArray(),dt=0.1,trajectories=1,saveat=1.0f0)
(p.len, p.nfacts) = (3, 1)
(p.len, p.nfacts) = (3, 1)
(p.len, p.nfacts) = (3, 1)
(p.len, p.nfacts) = (3, 1)
(p.len, p.nfacts) = (3, 1)
(p.len, p.nfacts) = (3, 1)
(p.len, p.nfacts) = (3, 1)
(p.len, p.nfacts) = (3, 1)
(p.len, p.nfacts) = (3, 1)
(p.len, p.nfacts) = (3, 1)
(p.len, p.nfacts) = (3, 1)
(p.len, p.nfacts) = (3, 1)
(p.len, p.nfacts) = (3, 1)
(p.len, p.nfacts) = (3, 1)
(p.len, p.nfacts) = (3, 1)
(p.len, p.nfacts) = (3, 1)
(p.len, p.nfacts) = (3, 1)
(p.len, p.nfacts) = (3, 1)
(p.len, p.nfacts) = (3, 1)
(p.len, p.nfacts) = (3, 1)
┌ Warning: dt <= dtmin. Aborting. There is either an error in your model specification or the true solution is unstable.
└ @ DiffEqBase ~/.julia/dev/DiffEqBase/src/integrator_interface.jl:162
EnsembleSolution Solution of length 1 with uType:
ODESolution{Float32,2,Array{Array{Float32,1},1},Nothing,Nothing,Array{Float32,1},Nothing,ODEProblem{Array{Float32,1},Tuple{Float32,Float32},true,Array{Float32,1},ODEFunction{true,typeof(lorenz),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem},TRBDF2{0,true,LinSolveGPUSplitFactorize,NLNewton{Rational{Int64},Rational{Int64},Rational{Int64}},DataType},DiffEqBase.LinearInterpolation{Array{Float32,1},Array{Array{Float32,1},1}},DiffEqBase.DEStats}
```
the prorgam doesn't enter this loop
```julia
    @loop for i in (0:(nfacts-1); (blockIdx().x-1) * blockDim().x + threadIdx().x)
        offset = i*len
        sv = SimpleView(offset, stride2)
        @cuprintf "\n\nouter factorization loop\n"
        generic_lufact!(W, sv, len)
        nothing
    end
```
So, I suspect that `for i in 0:0` doesn't iterate on GPU.

It looks very bizarre. Could it be that we accidentally smashed the stack?

**Comment by YingboMa** [comment]
```julia
julia> using CUDAnative, CuArrays, GPUifyLoops

julia> data = cu(ones(1));

julia> function kernel(A)
           @loop for i in (0:length(A)-1;
                           threadIdx().x)
               A[i+1] = 2*A[i+1]
           end
           @synchronize
       end
kernel (generic function with 1 method)

julia> data = cu(ones(1));

julia> @launch CUDA() kernel(data)

julia> data
1-element CuArray{Float32,1}:
 1.0

julia> function kernel2(A)
           @loop for i in (0:length(A)-1;
                           threadIdx().x-1)
               A[i+1] = 2*A[i+1]
           end
           @synchronize
       end
kernel2 (generic function with 1 method)

julia> @launch CUDA() kernel2(data)

julia> data
1-element CuArray{Float32,1}:
 2.0
```

The `0:0` issue is because of the bounds check. @vchuravy pointed out that
```julia
for I in (lhs;rhs)
```
Turns into:
```julia
for I in rhs
  boundscheck(lhs, I)
end
```

**Comment by YingboMa** [comment]
:tada: it now compiles and runs!

**Comment by YingboMa** [comment]
```julia
julia> sol1 = solve(monteprob,KenCarp4(linsolve=LinSolveGPUSplitFactorize()),EnsembleGPUArray(),dt=0.1,trajectories=2,saveat=1.0f0,abstol=1e-7,reltol=1e-8);

julia> sol2 = solve(monteprob,KenCarp4(linsolve=LinSolveGPUSplitFactorize()),EnsembleCPUArray(),dt=0.1,trajectories=2,saveat=1.0f0,abstol=1e-7,reltol=1e-8);

julia> sol1.u[1] - sol1.u[1]
3×101 Array{Float32,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
```

YES, THE RESULT IS ALSO CORRECT!

**Pull request merged**
